# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: Verify the specified codebase

on:
  pull_request: # verify on pull request
  push:
    branches:
    - master

jobs:
  verify:
    env:
      assumeInjectivityOnInhale: '1'
      checkConsistency: '0'
      headerOnly: 1
      includePaths: . verification/dependencies
      module: github.com/scionproto/scion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the VerifiedSCION repository
      uses: actions/checkout@v3
    - env:
        cache-name: gobra-cache
      name: Cache the verification results
      uses: actions/cache@v3
      with:
        key: ${{ env.cache-name }}
        path: ${{ runner.workspace }}/.gobra/cache.json
    - name: Verify the packages in the 'verification' directory
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ./dependencies/ ..
        module: ${{ env.module }}
        projectLocation: VerifiedSCION/verification
        recursive: 1
        timeout: 5m
    - name: Verify package 'pkg/addr'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/addr
        statsFile: /stats/stats_addr.json
        timeout: 10m
    - name: Verify package 'pkg/experimental/epic'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/experimental/epic
        timeout: 5m
    - name: Verify package 'pkg/log'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/log
        timeout: 5m
    - name: Verify package 'pkg/private/serrors'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/private/serrors
        timeout: 5m
    - name: Verify package 'pkg/scrypto'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/scrypto
        timeout: 5m
    - name: Verify package 'pkg/slayers'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/slayers
        timeout: 25m
    - name: Verify package 'pkg/slayers/path'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/slayers/path
        timeout: 10m
    - name: Verify package 'pkg/slayers/path/empty'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/slayers/path/empty
        timeout: 5m
    - name: Verify package 'pkg/slayers/path/epic'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/slayers/path/epic
        timeout: 10m
    - name: Verify package 'pkg/slayers/path/onehop'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/slayers/path/onehop
        timeout: 5m
    - name: Verify package 'pkg/slayers/path/scion'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: pkg/slayers/path/scion
        timeout: 5m
    - name: Verify package 'private/topology'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: private/topology
        timeout: 5m
    - name: Verify package 'private/underlay/conn'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: private/underlay/conn
        timeout: 5m
    - name: Verify package 'private/underlay/sockctrl'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: private/underlay/sockctrl
        timeout: 5m
    - name: Verify package 'router/'-both
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        disableMoreCompleteExhale: 1
        files: ' router/dataplane.go@229,837 router/metrics_spec.gobra router/dataplane_spec.gobra router/svc.go router/metrics.go router/svc_spec.gobra router/metrics_spec_test.gobra router/dataplane_spec_test.gobra router/svc_spec_test.gobra'
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        parallelizeBranches: 1
        timeout: 2h
    - name: Verify package 'router/'-none
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        files: ' router/dataplane.go@153,183,196,258,284,315,352,386,402,435,459,494,504,521,538,572,601,641,652,701,729,737,742,767,778,861,878,920,940,968,981,1071,1081,1106,1129,1148,1170,1217,1233,1240,1247,1272,1290,1309,1336,1345,1373,1390,1399,1417,1426,1463,1480,1555,1644,1668,1672,1677,1705,1757,1766,1785,1898,1904,1925,1952,1973,1995 router/metrics_spec.gobra router/dataplane_spec.gobra@122,155 router/svc.go@35,45,70,101,132 router/metrics.go@47 router/svc_spec.gobra router/metrics_spec_test.gobra router/dataplane_spec_test.gobra@26,37 router/svc_spec_test.gobra@25,32'
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        timeout: 2h
    - name: Verify package 'router/bfd'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: router/bfd
        timeout: 5m
    - name: Verify package 'router/control'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: router/control
        timeout: 5m
    - name: Upload the verification report
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: stats_addr.json
        path: /stats/stats_addr.json
