# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: Verify the specified codebase

on:
  push:
    branches:
    - master
  pull_request: # run this workflow on every pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      headerOnly: 1
      module: 'github.com/scionproto/scion'
      includePaths: '. verification/dependencies'
      assumeInjectivityOnInhale: '1'
      # Re-enable consistency checks when the "Remainder" predicates in slayers/path/scion
      # are changed to not include magic-wands.
      checkConsistency: '0'
    steps:
      - name: Checkout the VerifiedSCION repository
        uses: actions/checkout@v3
      - name: Cache the verification results
        uses: actions/cache@v3
        env:
          cache-name: gobra-cache
        with:
          path: ${{ runner.workspace }}/.gobra/cache.json
          key: ${{ env.cache-name }}
      # We split the verification of the entire repository into
      # multiple steps. This provides a more fine-grained log in
      # Github Workflow's interface and it allows more fine-grained
      # control over the settings applied to each package (this last
      # point could be also be solved by adapting the action to allow
      # per package config).
      - name: Verify package 'router/'
        uses: viperproject/gobra-action@dspil/test
        with:
          files: 'router/metrics_spec_test.gobra router/svc_spec_test.gobra router/dataplane_spec_test.gobra router/dataplane.go@192 router/dataplane_spec.gobra router/metrics.go router/metrics_spec.gobra router/svc.go router/svc_spec.gobra'
          timeout: 2h
          headerOnly: ${{ env.headerOnly }}
          module: ${{ env.module }}
          includePaths: ${{ env.includePaths }}
          assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
          checkConsistency: ${{ env.checkConsistency }}
          disableMoreCompleteExhale: 1
          parallelizeBranches: 1
      - name: Upload the verification report
        uses: actions/upload-artifact@v2
        with:
          name: stats_addr.json
          path: /stats/stats_addr.json
          if-no-files-found: error # could also be 'warn' or 'ignore'
