# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: Verify the specified codebase

on:
  pull_request: # verify on pull request
  push:
    branches:
    - master

jobs:
  verify:
    env:
      assumeInjectivityOnInhale: '1'
      checkConsistency: '0'
      headerOnly: 1
      includePaths: . verification/dependencies
      module: github.com/scionproto/scion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the VerifiedSCION repository
      uses: actions/checkout@v3
    - env:
        cache-name: gobra-cache
      name: Cache the verification results
      uses: actions/cache@v3
      with:
        key: ${{ env.cache-name }}
        path: ${{ runner.workspace }}/.gobra/cache.json
    - name: Verify package 'router/'-both
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        disableMoreCompleteExhale: 1
        files: "router/dataplane.go@229 router/router/metrics_spec.gobra router/router/dataplane_spec.gobra router/router/svc.go router/router/metrics.go router/router/svc_spec.gobra router/router/metrics_spec_test.gobra router/router/dataplane_spec_test.gobra router/router/svc_spec_test.gobra"
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        parallelizeBranches: 1
        timeout: 2h
    - name: Verify package 'router/'-none
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        files: ' router/dataplane.go@153,183,196,258,284,315,352,386,402,435,459,494,504,521,538,572,601,641,652,701,729,737,742,767,778,836,860,877,919,939,967,980,1070,1080,1105,1128,1147,1169,1216,1232,1239,1246,1271,1289,1308,1335,1344,1372,1389,1398,1416,1425,1462,1479,1554,1643,1667,1671,1676,1704,1756,1765,1784,1897,1903,1924,1951,1972,1994 router/router/metrics_spec.gobra router/dataplane_spec.gobra@122,155 router/svc.go@35,45,70,101,132 router/metrics.go@47 router/router/svc_spec.gobra router/router/metrics_spec_test.gobra router/dataplane_spec_test.gobra@26,37 router/svc_spec_test.gobra@25,32'
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        timeout: 2h
    - name: Verify package 'router/bfd'
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: router/bfd
        timeout: 5m
    - name: Verify package 'router/control'
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        packages: router/control
        timeout: 5m
    - name: Upload the verification report
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: stats_addr.json
        path: /stats/stats_addr.json
