# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: Verifying function pkg/slayers/path/onehop/onehop.go:ToSCIONDecoded

on:
  pull_request: # verify on pull request
  push:
    branches:
    - master

jobs:
  verify:
    env:
      assumeInjectivityOnInhale: '1'
      checkConsistency: '0'
      headerOnly: 1
      includePaths: . verification/dependencies
      module: github.com/scionproto/scion
      parallelizeBranches: '1'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the VerifiedSCION repository
      uses: actions/checkout@v3
    - env:
        cache-name: gobra-cache
      name: Cache the verification results
      uses: actions/cache@v3
      with:
        key: ${{ env.cache-name }}
        path: ${{ runner.workspace }}/.gobra/cache.json
    - name: Verify package 'pkg/slayers/path/onehop'
      uses: viperproject/gobra-action@main
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        files: ' pkg/slayers/path/onehop/onehop.go@159 pkg/slayers/path/onehop/onehop_spec.gobra pkg/slayers/path/onehop/onehop_spec_test.gobra'
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        parallelizeBranches: ${{ env.parallelizeBranches }}
        timeout: 10m
