jobs:
  verify:
    env:
      assumeInjectivityOnInhale: '1'
      checkConsistency: '0'
      headerOnly: 1
      includePaths: . verification/dependencies
      module: github.com/scionproto/scion
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the VerifiedSCION repository
      uses: actions/checkout@v3
    - env:
        cache-name: gobra-cache
      name: Cache the verification results
      uses: actions/cache@v3
      with:
        key: ${{ env.cache-name }}
        path: ${{ runner.workspace }}/.gobra/cache.json
    - name: Verify the packages in the 'verification' directory
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        headerOnly: ${{ env.headerOnly }}
        includePaths: ./dependencies/ ..
        module: ${{ env.module }}
        projectLocation: VerifiedSCION/verification
        recursive: 1
        timeout: 5m
    - name: Verify package 'router/'-both
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        disableMoreCompleteExhale: 1
        files: ' router/router/dataplane.go@223 router/router/metrics_spec.gobra router/router/dataplane_spec.gobra router/router/svc.go router/router/metrics.go router/router/svc_spec.gobra router/router/metrics_spec_test.gobra router/router/dataplane_spec_test.gobra router/router/svc_spec_test.gobra'
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        parallelizeBranches: 1
        timeout: 2h
    - name: Verify package 'router/'-none
      uses: viperproject/gobra-action@dspil/test
      with:
        assumeInjectivityOnInhale: ${{ env.assumeInjectivityOnInhale }}
        checkConsistency: ${{ env.checkConsistency }}
        files: ' router/router/dataplane.go@149,179,192,244,265,296,333,367,383,416,440,475,485,502,519,553,582,622,633,682,710,718,723,748,759,816,833,850,892,912,940,953,1043,1051,1076,1099,1118,1140,1187,1203,1210,1217,1242,1260,1279,1306,1315,1343,1360,1369,1387,1396,1433,1450,1525,1614,1638,1642,1647,1675,1727,1736,1755,1868,1874,1895,1922,1943,1965 router/router/metrics_spec.gobra router/router/dataplane_spec.gobra@107 router/router/svc.go@35,45,70,101,132 router/router/metrics.go@47 router/router/svc_spec.gobra router/router/metrics_spec_test.gobra router/router/dataplane_spec_test.gobra@25 router/router/svc_spec_test.gobra@25,32'
        headerOnly: ${{ env.headerOnly }}
        includePaths: ${{ env.includePaths }}
        module: ${{ env.module }}
        timeout: 2h
    - name: Upload the verification report
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: stats_addr.json
        path: /stats/stats_addr.json
name: Verify the specified codebase
'on':
  pull_request: 1
  push:
    branches:
    - master
